FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

# FROM nginx
# RUN rm /etc/nginx/conf.d/default.conf
# COPY content /usr/share/nginx/html
# COPY conf /etc/nginx